//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id_Adress { get; set; }
        public Nullable<int> Number { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Postal_Code { get; set; }
        public int Id_Profil_User { get; set; }
    
        public virtual Profil_User Profil_User { get; set; }
    }
}
