//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreProjectData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreProjectEntities : DbContext
    {
        public StoreProjectEntities()
            : base("name=StoreProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Products_Type> Products_Type { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Products_Photo> Products_Photo { get; set; }
        public virtual DbSet<Products_Price> Products_Price { get; set; }
        public virtual DbSet<Profil_User> Profil_User { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Sales_Products> Sales_Products { get; set; }
    }
}
